### ISSUE TITLE
Sporočilo commita za 2. domačo nalogo

### ISSUE THREAD

**Issue by katjabercic** [UrbanusBecanus/racunalniski-praktikum#2]
Za točko pri 2. domači nalogi mora v repozitoriju biti commit s sporočilom `2. domača naloga`, v vašem repozitoriju pa je samo commit s sporočilom `Domoča naloga2.`.

Lep pozdrav,
Katja

**Comment by UrbanusBecanus** [comment]
Pozdravljeni.

Commit je popravljen.

Lep pozdrav
Urban
